### ISSUE TITLE
[1.15pre4] the smoke is especially colorful and good

### ISSUE THREAD

**Issue by Yoghurt4C** [kyrptonaught/Colored-Campfire#1]
![image](https://user-images.githubusercontent.com/11313954/70165575-323da500-16d4-11ea-80b6-a77963a9bb3e.png)

**Comment by kyrptonaught** [comment]
It’s a feature

**Comment by kyrptonaught** [comment]
Does it work on previous pre-releases?

**Comment by Yoghurt4C** [comment]
no clue, only tested in pre4

**Comment by kyrptonaught** [comment]
Version 1.1.0 has been released on curseforge containing the fix.
https://www.curseforge.com/minecraft/mc-mods/colorful-campfire-smoke/files/2836728

Smoke is no longer as colorful and good tho
