### ISSUE TITLE
[1.15] broken in smp

### ISSUE THREAD

**Issue by Yoghurt4C** [kyrptonaught/Colored-Campfire#2]
campfires stop producing smoke when a redstone signal is applied to them, possibly caused by the lack of a custom packet telling the client what to render

**Comment by kyrptonaught** [comment]
Assuming you mean on a multiplayer server. 
I guess this means that the client doesnot know if a block is being redstone powered or not, I could’ve sworn it did. Will investigate a fix, I want to keep this a client side only mod

**Comment by kyrptonaught** [comment]
Fixed in 1.1.2
