### ISSUE TITLE
Crash on 1.16.4

### ISSUE THREAD

**Issue by isaacisnotjonah** [kyrptonaught/Colored-Campfire#3]
Seems to be an error with the code injection.
Have verified with a clean install and latest fabric api.
[crash-2020-11-29_10.50.38-client.txt](https://github.com/kyrptonaught/Colored-Campfire/files/5611410/crash-2020-11-29_10.50.38-client.txt)

**Comment by kyrptonaught** [comment]
Ah yeah, something must've broke recently, I'll check it tomorrow morning

**Comment by isaacisnotjonah** [comment]
Okay, thank you very much!

**Comment by kyrptonaught** [comment]
This has been fixed in 1.1.5. Curse is a bit slow so here's a jar for now, also working on getting it on modrinth
[coloredcampfire-1.1.5-1.16.zip](https://github.com/kyrptonaught/Colored-Campfire/files/5612106/coloredcampfire-1.1.5-1.16.zip)

**Comment by kyrptonaught** [comment]
Nvm it got approved instantly

**Comment by isaacisnotjonah** [comment]
Great! Thanks so much for a great mod and a fast fix!
Edit: tested (to be sure), and it works! Closing issue.
